# Generated by Django 5.0.3 on 2024-03-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.SmallIntegerField(max_length=20),
        ),
    ]
